### ISSUE TITLE
UserManager.CreateAsync not creating a user in the LiteDB database

### ISSUE THREAD

**Issue by woaksie** [fabian-blum/AspNetCore.Identity.LiteDB#12]
I am trying to get AspNetCore.Identity.LiteDB working in a Server Blazor app. I have been using the demo project for reference. I have hooked up code and call UserManager.CreateAsync(user, password). This returns an IdentityResult.Succeeded.

When I check the database I see that the users collection has been created but it contains no records and I cannot login in my app.

If I call UserManager.FindByNameAsync(username) nothing is returned. I feel like I am missing something.

    private async void Register()
    {
        var user = new ApplicationUser
        {
            UserName = UserName,
            Email = Email,
        };

        IdentityResult result = await UserManager.CreateAsync(user, Password1);

        if (result.Succeeded)
        {
               // this passes
        }
   }

**Comment by zblesk** [comment]
I had the same thing happening. For me, it disappeared when I changed the ClaimsIdentity.UserIdClaimType to a custom value. That makes no sense, and I'm not sure whether it actually helped, or I just changed something else I don't know about, or something else entirely. But it seems to work now.

**Comment by vlad-chigrinov** [comment]
I have the same problem. Have you found a solution?

**Comment by vlad-chigrinov** [comment]
I have solved this problem: I copied AspNetCore.Identity.LiteDB project to my solution, add Microsoft.Extensions.Configuration package and updated the packages Microsoft.Extensions.Identity.Core, Microsoft.Extensions.Identity.Stores, LiteDB

**Comment by fabian-blum** [comment]
Fixed in latest version 4.0.0
