### ISSUE TITLE
Reference to Microsoft.AspNetCore.Identity.EntityFrameworkCore?

### ISSUE THREAD

**Issue by weitzhandler** [fabian-blum/AspNetCore.Identity.LiteDB#4]
Is the dependency this project has on `Microsoft.AspNetCore.Identity.EntityFrameworkCore` really necessary? I think the whole idea is to get passed EF and not be dependent on it.

How about `Newtonsoft.Json`? I think if `LiteDb` itself can manage without it, this repo can do just as well.

**Comment by fabian-blum** [comment]
Reference was removed in the newest version. Please checkout version 3.1.0 on nuget.
