### ISSUE TITLE
Doesnt work with LiteDb 5.x

### ISSUE THREAD

**Issue by HolyOne** [fabian-blum/AspNetCore.Identity.LiteDB#7]
I get error

An unhandled exception occurred while processing the request.
MissingMethodException: Method not found: 'LiteDB.LiteCollection`1<!!0> LiteDB.LiteDatabase.GetCollection(System.String)'.

**Comment by fabian-blum** [comment]
Nuget Packages have been updated to LiteDb 5. Please check version 3.1.0 on nuget.
