### ISSUE TITLE
Where to place the database securely?

### ISSUE THREAD

**Issue by diegosasw** [fabian-blum/AspNetCore.Identity.LiteDB#9]
Where to place the LiteDb database file in a web application?
I can see in the demo project that it's under an App_Data folder within wwwroot. 

https://github.com/fabian-blum/AspNetCore.Identity.LiteDB/blob/master/AspNetCore.Identity.LiteDB/AspNetCore.Identity.LiteDB.Demo/appsettings.json

I cannot find documentation about the safety of that location. I know in previous versions it was like this.

But currently I've seen some samples where App_Data is outside wwwroot folder.
https://edi.wang/post/2018/10/31/migrating-old-aspnet-applications-to-net-core

Is it safe having it at `"DefaultConnection": "Filename=wwwroot/App_Data/LiteDbIdentity.db"`?

**Comment by fabian-blum** [comment]
Hey. Sorry for the late response. I fixed this in the demo application.
In .NET Core the App_Data folder is no langer "only for the application".
It's better to store the db localy -> for example the root app folder     "DefaultConnection": "LiteDbIdentity.db"
